; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = native_app

[env:esp8266_app]
platform = espressif8266
framework = arduino
board = esp07
upload_speed = 921600
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
monitor_filters = log2file
build_src_filter = +<*> -<native_app/>
build_flags = 
    -Ilib/lib_common/Log
    -Ilib/lib_common/FSManager
lib_ignore = lib_native
lib_extra_dirs = 
	lib/lib_esp8266/
	lib/lib_common/
board_build.filesystem = littlefs
lib_deps = 
	adafruit/Adafruit AHTX0@^2.0.5
	bodmer/TFT_eSPI@^2.5.43

[env:nodemcu_app]
platform = espressif8266
framework = arduino
board = nodemcuv2
upload_speed = 921600
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
monitor_filters = log2file
build_src_filter = +<*> -<native_app/>
build_flags = 
    -Ilib/lib_common/Log
    -Ilib/lib_common/FSManager
lib_ignore = lib_native
lib_extra_dirs = 
	lib/lib_esp8266/
	lib/lib_common/
board_build.filesystem = littlefs
lib_deps = 
	adafruit/Adafruit AHTX0@^2.0.5
	bodmer/TFT_eSPI@^2.5.43
	Lib/lib_common/EventLib
	

[env:native_app]
platform = native
build_src_filter = +<*> -<esp8266_app/>
build_flags = 
	-std=c++20
	-lws2_32
    -Ilib/lib_common/Log
lib_archive = yes
lib_ldf_mode = deep+
lib_ignore = lib_esp8266
lib_extra_dirs = 
	lib/lib_native/
	lib/lib_common/
extra_scripts = copy_data.py

[env:unity_test]
platform = native
build_flags = 
	-std=c++20
lib_ignore = 
	lib_esp8266
lib_extra_dirs = 
	lib/lib_native/
	lib/lib_common/
